---
application:
  name: "projectsample1"
  project: "isvsample"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "isvdatabase"
  version: "12"
routers:
- name: "main-projectsample1"
  routes:
  - application_name: "projectsample1"
    paths:
    - "/*"
